### ISSUE TITLE
Script incorrectly choose folder with certificates

### ISSUE THREAD

**Issue by paskal** [nginx-le/nginx-le#22]
Good day!
After migration to other server my letencrypt started using other folder than original and nginx-le logic broke:
```
[root@terrty ~]# ll letsencrypt/live/
total 8
drwxr-xr-x 2 root root 4096 Nov 18 12:08 terrty.net/
drwxr-xr-x 2 root root 4096 Nov 18 12:21 terrty.net-0001/
```
Don't you mind if I'll prepare a patch which will use latest from `domain|domain-/d{4}` directories available?
It's a mess to fix these with bare hands and to debug what's wrong now: script writes that it renewed a certificate, but copies from wrong `live` folder to `/etc/nginx/ssl`.

**Comment by umputun** [comment]
Confused. How did you get both `terrty.net` and `terrty.net-0001` here? In order to achieve this, you should run certbot twice with different params but for the same domain?

You said "after migration" but how exactly did you do the migration? I don't think you even need any migration, but the only thing needed is a fresh install of ngnix-le on the new host.

Generally speaking, I don't understand the root cause, however picking latest directory feels like a hack to me. Maybe defining directory explicitly will help? 

```
paths:
  Flags for changing execution paths & servers

  --cert-path CERT_PATH
                        Path to where certificate is saved (with auth --csr),
                        installed from, or revoked. (default: None)
  --key-path KEY_PATH   Path to private key for certificate installation or
                        revocation (if account key is missing) (default: None)
  --fullchain-path FULLCHAIN_PATH
                        Accompanying path to a full certificate chain
                        (certificate plus chain). (default: None)
  --chain-path CHAIN_PATH
                        Accompanying path to a certificate chain. (default:
                        None)
  --config-dir CONFIG_DIR
                        Configuration directory. (default: /etc/letsencrypt)
  --work-dir WORK_DIR   Working directory. (default: /var/lib/letsencrypt)
  --logs-dir LOGS_DIR   Logs directory. (default: /var/log/letsencrypt)
  --server SERVER       ACME Directory Resource URI. (default:
                        https://acme-v02.api.letsencrypt.org/directory)
```

https://certbot.eff.org/docs/using.html#certbot-command-line-options

**Comment by paskal** [comment]
It happens only if you mount /etc/letsencrypt folder, which is not recommended by docker-compose.yaml. It made sense only before https://github.com/umputun/nginx-le/pull/14 and just breaking things now.
Resolving, sorry for taking your time.
